In [2]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score

In [3]:
data = pd.read_csv('heart(1).csv', delimiter=';', header=0)
data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
##pengecekan data
print(data.isnull().any())
print(data.isnull().sum())

Age               False
Sex               False
ChestPainType     False
RestingBP         False
Cholesterol       False
FastingBS         False
RestingECG        False
MaxHR             False
ExerciseAngina    False
Oldpeak           False
ST_Slope          False
HeartDisease      False
dtype: bool
Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
enc = LabelEncoder()

In [7]:
data['Age']=enc.fit_transform(data['Age'].values)
data['Sex']=enc.fit_transform(data['Sex'].values)
data['ChestPainType']=enc.fit_transform(data['ChestPainType'].values)
data['RestingBP']=enc.fit_transform(data['RestingBP'].values)
data['Cholesterol']=enc.fit_transform(data['Cholesterol'].values)
data['FastingBS']=enc.fit_transform(data['FastingBS'].values)
data['RestingECG']=enc.fit_transform(data['RestingECG'].values)
data['MaxHR']=enc.fit_transform(data['MaxHR'].values)
data['ExerciseAngina']=enc.fit_transform(data['ExerciseAngina'].values)
data['Oldpeak']=enc.fit_transform(data['Oldpeak'].values)
data['ST_Slope']=enc.fit_transform(data['ST_Slope'].values)

In [8]:
trs_data=data.drop(columns='HeartDisease')
trs_data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,12,1,1,35,134,0,1,93,0,10,2
1,21,0,2,48,33,0,1,79,0,19,1
2,9,1,1,25,129,0,2,24,0,10,2
3,20,0,0,33,63,0,1,33,1,24,1
4,26,1,2,42,45,0,1,47,0,10,2

In [9]:
lbl_data=data['HeartDisease']
lbl_data.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [10]:
#membagi data training dan testing -> 0.3 dan 0,7 data train dan di random sebanyak 500 kali
X_train, X_test, Y_train, Y_test = train_test_split(trs_data,lbl_data,test_size=0.2,random_state=2)
classifier=GaussianNB()
classifier.fit(X_train,Y_train)
y_pred=classifier.predict(X_test)

In [11]:
print('Accuracy of Naive Bayes Continue classifier on test set: {:.2f}'.format(classifier.score(X_test,Y_test)))
print(confusion_matrix(Y_test,y_pred))
print(accuracy_score(Y_test,y_pred))
hasilpengujian=classification_report(Y_test,y_pred)
print(hasilpengujian)

Accuracy of Naive Bayes Continue classifier on test set: 0.84
[[40  7]
 [12 61]]
0.8416666666666667
              precision    recall  f1-score   support

           0       0.77      0.85      0.81        47
           1       0.90      0.84      0.87        73

    accuracy                           0.84       120
   macro avg       0.83      0.84      0.84       120
weighted avg       0.85      0.84      0.84       120